---
title: "Notes"
editor: visual
resources: AnalisiComplessa/AnComp.pdf
           ProbabilityNotes/ProbabilityNotes.pdf
           TesiTriennale/TesiTriennale.pdf
           TesiTriennale/TesiTriennalePresentazioneFrancescoMussin866633.pdf
---

Throughout my academic carreer I have been making LaTeX notes on essentially every course I took. This was a way to store everything I needed to know digitally. Too much later I realized that the best way to do that was with a site, so here we are: no more phisical notebooks or tex files that aren't stored on all my devices, here I can access everything I want.

## Notes from courses from my bachelor's studies

This is a collection of LaTeX notes taken from courses taught at UniMiB when I was a mathematics Bachelor's student. ***They are only available in italian*** as that was the language of instruction of the material.

-   [📖 Analisi Complessa](AnalisiComplessa/AnComp.pdf)
-   [📖 Teoria della Probabilità](ProbabilityNotes/ProbabilityNotes.pdf)
-   [📖 La mia Tesi Triennale](TesiTriennale/TesiTriennale.pdf)
-   [📖 La presentazione della mia Tesi Triennale](TesiTriennale/TesiTriennalePresentazioneFrancescoMussin866633.pdf)

## Notes from courses from my Master's studies

This is a collection of LaTeX notes taken from courses taught at ETHZ during my attendance.

-   [📖 Read my notes on Information Theory]() (under construction)
-   [📖 Read my notes on Statistical Learning]() (under construction)

## Other notes

These are just notes on things I'm learning about.

-   [📖 Read my notes on Randomized Numerical Linear Algebra]() (under construction)
